# Generated by Django 4.1.6 on 2023-02-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_heroheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='heroHeader',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
