# Generated by Django 4.1.6 on 2023-02-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_heroheader_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comBody',
        ),
    ]
