# Generated by Django 4.1.6 on 2023-02-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_body_comment_combody'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewCount',
            field=models.IntegerField(default=0),
        ),
    ]
