# Generated by Django 4.1.6 on 2023-02-14 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_combody_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downVote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='upVote',
            field=models.IntegerField(default=0),
        ),
    ]
